//Order actions
export const ADD_TO_ORDER = 'ADD_TO_ORDER';
export const REMOVE_FROM_ORDER = 'REMOVE_FROM_ORDER';
export const CLEAR_CART = 'CLEAR_CART';
export const CALC_AMOUNTS = 'CALC_AMOUNTS';
export const SAVE_ORDER_ID = 'SAVE_ORDER_ID';
export const SAVE_CUSTOMER_INFO = 'SAVE_CUSTOMER_INFO';
export const FETCH_ALL_ORDERS = 'FETCH_ALL_ORDERS';
export const SUBMIT_ORDER_START = 'SUBMIT_ORDER_START';
export const SUBMIT_ORDER_SUCCESS = 'SUBMIT_ORDER_START';
export const SUBMIT_ORDER_FAILED = 'SUBMIT_ORDER_START';
export const SUBMIT_ORDER = 'SUBMIT_ORDER'

//Menu actions
export const FETCH_CATEGORIES_START = 'FETCH_CATEGORIES_START';
export const FETCH_CATEGORIES_SUCCESS = 'FETCH_CATEGORIES_SUCCESS';
export const FETCH_CATEGORIES_FAILED = 'FETCH_CATEGORIES_FAILED';
export const FETCH_SUB_CATEGORIES_START = 'FETCH_SUB_CATEGORIES_START';
export const FETCH_SUB_CATEGORIES_SUCCESS = 'FETCH_SUB_CATEGORIES_SUCCESS';
export const FETCH_SUB_CATEGORIES_FAILED = 'FETCH_SUB_CATEGORIES_FAILED';
export const FETCH_MENU_START = 'FETCH_MENU_START';
export const FETCH_MENU_SUCCESS = 'FETCH_MENU_SUCCESS';
export const FETCH_MENU_FAILED = 'FETCH_MENU_FAILED';

//Authentication actions
export const AUTH_START = 'AUTH_START'
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';
export const AUTH_SET_REDIRECT_PATH = 'AUTH_SET_REDIRECT_PATH';